# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03b25a3e11fc44228d533382668345f1325a7fe557c8c462c2aae82c3a6cea7087f77387f87fa7e57cc2390158b74826a0e85f78fba03d44fa970b2f3bf101df

test:
  secret_key_base: ea7b5024cfe49add986da275b999bcc69679c5045a25458389589da83e67c2c2deca5117ccbda393a3fa25a722d165d1f2bbd80077074bf54cd50674c5c514bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
